on: pull_request
name: Test and build
jobs:
  flutter-mobile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17.x"
          distribution: "temurin"
      - uses: subosito/flutter-action@v2
      - name: Build apk
        run: |
          flutter upgrade
          flutter pub get
          dart format --set-exit-if-changed .
          flutter analyze
          flutter test --dart-define=golden_tolerance=0.1
          flutter build apk --debug
  