on: pull_request
name: Test and build
jobs:
  flutter-mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17.x"
          distribution: "temurin"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'
      - name: Build apk
        run: |
          echo "${{ secrets.FIREBASE_OPTIONS }}" | base64 -d > ./lib/firebase_options.dart
          flutter pub get
          dart format --set-exit-if-changed .
          flutter analyze
          flutter test --dart-define=golden_tolerance=0.1 --update-goldens
          flutter build apk --debug
  